"""
Big Data Analysis Project
Complete Python Script
Dataset used: Online Retail Dataset (UCI Machine Learning Repository)
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
url = "dataset.xlsx"
df = pd.read_excel(url)

# --- Data Cleaning ---
df_clean = df.dropna(subset=["CustomerID"])        # Remove rows with missing CustomerID
df_clean = df_clean[df_clean["Quantity"] > 0]      # Remove negative or zero quantities
df_clean["InvoiceDate"] = pd.to_datetime(df_clean["InvoiceDate"])  # Convert to datetime
df_clean["TotalAmount"] = df_clean["Quantity"] * df_clean["UnitPrice"]

# --- Business Insights ---
# Insight 1: Top 10 highest revenue products
top_products = (
    df_clean.groupby("Description")["TotalAmount"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

# Insight 2: Monthly sales trend
monthly_sales = (
    df_clean.set_index("InvoiceDate")
    .resample("ME")["TotalAmount"]
    .sum()
)

# --- Visualizations ---

# Top Products Bar Chart (Save as Image)
plt.figure(figsize=(10, 5))
top_products.plot(kind="bar")
plt.title("Top 10 Products by Revenue")
plt.xlabel("Product")
plt.ylabel("Revenue")
plt.tight_layout()
plt.savefig("top_10_products.png")   # <-- saves chart as PNG
plt.close()

# Monthly Sales Trend Line Chart (Save as Image)
plt.figure(figsize=(10, 5))
monthly_sales.plot()
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Revenue")
plt.tight_layout()
plt.savefig("monthly_sales_trend.png")   # <-- saves chart as PNG
plt.close()

# --- Summary ---
summary = """
Key Insights:
1. The highest revenue is generated by a small group of top-selling products.
2. Monthly sales trends highlight demand patterns over time.

How Big Data Helps:
- Identifies hidden patterns for better decisions.
- Predicts customer needs and improves forecasting.
- Boosts profitability by focusing on best-performing products.
"""

print(summary)
